spring.application.name=B-Ball-insight

# ========================
# PostgreSQL Configuration
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/bball_insight
spring.datasource.username=postgres
spring.datasource.password=kapy2019
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# BallDontLie API
# ========================
balldontlie.api.key=YOUR_API_KEY_HERE
balldontlie.api.base-url=https://api.balldontlie.io/v1

# ========================
# Server
# ========================
server.port=8080
